
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  postgres:
    build: postgres
    image: rbiedrawa/ksqldb-postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      APP_DB_USER: cdcdemo
      APP_DB_PASS: cdcdemo
      APP_DB_NAME: demo_db
    ports:
      - 6532:6532
      - 5433:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 7775:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: postgres

  kowl:
    image: quay.io/cloudhut/kowl:v1.3.1
    restart: on-failure
    container_name: kowl
    ports:
        - "8080:8080"
    depends_on:
        - kafka
    environment:
      KAFKA_BROKERS: "kafka:29092"
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081"

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.7
    hostname: kafka-connect-ui
    container_name: kafka-connect-ui
    ports:
        - "8000:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083"
    depends_on:
        - kafka-connect

  # kafka-connect:
  #   image: debezium/connect:2.3
  #   hostname: kafka-connect
  #   container_name: kafka-connect
  #   depends_on:
  #     - postgres
  #     - zookeeper
  #     - kafka
  #     - schema-registry
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
  #     CONNECT_REST_PORT: 8083
  #     CONNECT_GROUP_ID: "kafka-connect-group1"
  #     CONNECT_CONFIG_STORAGE_TOPIC: "_kafka_connect_group1-configs"
  #     CONNECT_OFFSET_STORAGE_TOPIC: "_kafka_connect_group1-offsets"
  #     CONNECT_STATUS_STORAGE_TOPIC: "_kafka_connect_group1-status"
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  #     CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
  #     CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
  #   command:
  #     - bash
  #     - -c
  #     - |
  #       echo "Installing connector plugins"
  #       confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.5.0
  #       #
  #       echo "Launching Kafka Connect worker"
  #       /etc/confluent/docker/run &
  #       #
  #       echo "Waiting for Kafka Connect to start listening on localhost:8083 ⏳"
  #       while : ; do
  #           curl_status=$$(curl -s -o /dev/null -w %{http_code} http://localhost:8083/connectors)
  #           echo -e $$(date) " Kafka Connect listener HTTP state: " $$curl_status " (waiting for 200)"
  #           if [ $$curl_status -eq 200 ] ; then
  #           break
  #           fi
  #           sleep 5
  #       done
  #       echo -e "\n--\n+> Creating Kafka Connect source"
  #       curl -i -X PUT -H "Accept:application/json" \
  #           -H  "Content-Type:application/json" \
  #           http://localhost:8083/connectors/postgres-cdc-demo/config \
  #           -d '{
  #             "name": "postgres-cdc-demo",
  #             "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  #             "database.hostname": "postgres",
  #             "database.port": "5432",
  #             "database.user": "postgres",
  #             "database.password": "postgres",
  #             "database.server.name": "DockerServer",
  #             "database.dbname": "demo_db",
  #             "tasks.max": "1"
  #         }'
  #       #
  #       #
  #       sleep infinity
  kafka-connect:
    image: debezium/connect:2.3
    container_name: kafka-connect
    depends_on:
      - postgres
      - kafka
      - zookeeper
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:29092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_statuses"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      ENABLE_DEBEZIUM_SCRIPTING: "true"
